### ISSUE TITLE
Issue with paths when installed through poetry

### ISSUE THREAD

**Issue by Hiyorimi** [sky-ring/rift#7]
I installed dependencies with poetry with:

```bash
~/.pyenv/versions/3.10.7/bin/python3.10 -m poetry install
~/.pyenv/versions/3.10.7/bin/poetry run pip install -e .
```

Trying to get testing project up I faced following:

```bash
~/.pyenv/versions/3.10.7/bin/poetry run rift init testing-rift
PermissionError: [Errno 13] Permission denied: './testing-rift/contracts/testing-rift.py'
```

I assume there must be some issue when using python with a relative path.

UPD: folders were created.

**Comment by AminRezaei0x443** [comment]
As this is a permission error, can you test it with the usual pip installation to see whether it works or not?

```
~/.pyenv/versions/3.10.7/bin/python3.10 -m pip install rift-framework
~/.pyenv/versions/3.10.7/Scripts/rift init testing-rift
```

**Comment by Hiyorimi** [comment]
> init testing-rift

You was right:

```bash
(testing-rift-py3.10) ➜  testing_rift which rift                                                                                              15.09.22 10:33
~/virtualenvs/testing-rift-eisqpOW1-py3.10/bin/rift
(testing-rift-py3.10) ➜  testing_rift rift init testing-rift                                                                                  15.09.22 10:34
Initializing new rift project ...
Traceback (most recent call last):
  File "~/virtualenvs/testing-rift-eisqpOW1-py3.10/bin/rift", line 8, in <module>
    sys.exit(entry())
  File "~/virtualenvs/testing-rift-eisqpOW1-py3.10/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "~/virtualenvs/testing-rift-eisqpOW1-py3.10/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "~/virtualenvs/testing-rift-eisqpOW1-py3.10/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "~/virtualenvs/testing-rift-eisqpOW1-py3.10/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "~/virtualenvs/testing-rift-eisqpOW1-py3.10/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "~/virtualenvs/testing-rift-eisqpOW1-py3.10/lib/python3.10/site-packages/rift/cli/commands/init.py", line 29, in init
    write_contract(base, pjoin(path, name, "contracts", f"{name}.py"))
  File "~/virtualenvs/testing-rift-eisqpOW1-py3.10/lib/python3.10/site-packages/rift/bases/util.py", line 18, in write_contract
    fd = open(dst, "w")
PermissionError: [Errno 13] Permission denied: './testing-rift/contracts/testing-rift.py'
(testing-rift-py3.10) ➜  testing_rift ~/virtualenvs/testing-rift-eisqpOW1-py3.10/bin/rift init testing-rift 15.09.22 10:34
Initializing new rift project ...
Error creating project, dir exists!
(testing-rift-py3.10) ➜  testing_rift ls                                                                                                      15.09.22 10:34
poetry.lock    pyproject.toml testing-rift   toad-token
```

**Comment by AminRezaei0x443** [comment]
Please remove the `testing-rift` directory and try again so we can see if it works fine with the `rift` bin or not. or just test with new project name.

**Comment by Hiyorimi** [comment]
> Please remove the `testing-rift` directory and try again so we can see if it works fine with the `rift` bin or not. or just test with new project name.

Same error persist with both, running `rift` from shell and running the binary directly.
